export const DEFAULT_PASSWORD = "Trailang123";
export const APP_NAME = "Trai Làng FC";
export const APP_TIMEZONE = "Asia/Ho_Chi_Minh";

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  MEMBERS_VIEW: "members.view",
  MEMBERS_MANAGE: "members.manage",
  MEMBER_PROFILE_EDIT_OWN: "member_profile.edit_own",
  CHARGES_VIEW_OWN: "charges.view_own",
  CHARGES_VIEW_ALL: "charges.view_all",
  CHARGES_MANAGE: "charges.manage",
  PAYMENTS_VIEW_OWN: "payments.view_own",
  PAYMENTS_VIEW_ALL: "payments.view_all",
  PAYMENTS_MANAGE: "payments.manage",
  EXPENSES_VIEW: "expenses.view",
  EXPENSES_MANAGE: "expenses.manage",
  MATCHES_VIEW: "matches.view",
  MATCHES_MANAGE: "matches.manage",
  MATCH_SEED_VIEW: "match_seed.view",
  MATCH_SEED_MANAGE: "match_seed.manage",
  MATCH_TEAMS_VIEW: "match_teams.view",
  MATCH_TEAMS_MANAGE: "match_teams.manage",
  MATCH_FORM_REPORT_VIEW: "match_form_report.view",
  CLUB_BALANCE_VIEW: "club_balance.view",
  OTHER_MEMBER_BALANCES_VIEW: "member_balances.view_all",
  SETTINGS_MANAGE: "settings.manage",
  USERS_MANAGE: "users.manage",
  AUDIT_VIEW: "audit.view",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_DEFINITIONS: Array<{
  key: PermissionKey;
  name: string;
  description: string;
}> = [
  { key: PERMISSIONS.DASHBOARD_VIEW, name: "Xem tổng quan", description: "Truy cập dashboard" },
  { key: PERMISSIONS.MEMBERS_VIEW, name: "Xem thành viên", description: "Xem danh sách thành viên" },
  { key: PERMISSIONS.MEMBERS_MANAGE, name: "Quản lý thành viên", description: "Thêm và cập nhật thành viên" },
  { key: PERMISSIONS.MEMBER_PROFILE_EDIT_OWN, name: "Sửa hồ sơ cá nhân", description: "Sửa CV và avatar của thành viên đang liên kết" },
  { key: PERMISSIONS.CHARGES_VIEW_OWN, name: "Xem khoản thu cá nhân", description: "Yêu cầu tài khoản liên kết với một thành viên" },
  { key: PERMISSIONS.CHARGES_VIEW_ALL, name: "Xem toàn bộ khoản thu", description: "Xem khoản phải đóng của cả đội" },
  { key: PERMISSIONS.CHARGES_MANAGE, name: "Quản lý khoản thu", description: "Tạo, sửa và xóa khoản phải đóng" },
  { key: PERMISSIONS.PAYMENTS_VIEW_OWN, name: "Xem tiền nộp cá nhân", description: "Yêu cầu tài khoản liên kết với một thành viên" },
  { key: PERMISSIONS.PAYMENTS_VIEW_ALL, name: "Xem toàn bộ tiền nộp", description: "Xem tiền nộp của cả đội" },
  { key: PERMISSIONS.PAYMENTS_MANAGE, name: "Quản lý tiền nộp", description: "Ghi nhận, sửa và xóa tiền nộp" },
  { key: PERMISSIONS.EXPENSES_VIEW, name: "Xem thu chi", description: "Xem giao dịch thực tế của club" },
  { key: PERMISSIONS.EXPENSES_MANAGE, name: "Quản lý thu chi", description: "Tạo, sửa và xóa thu chi" },
  { key: PERMISSIONS.MATCHES_VIEW, name: "Xem trận", description: "Xem lịch sử trận và người tham gia" },
  { key: PERMISSIONS.MATCHES_MANAGE, name: "Quản lý trận", description: "Tạo và cập nhật trận" },
  { key: PERMISSIONS.MATCH_SEED_VIEW, name: "Xem seed theo trận", description: "Xem đánh giá Tier 1–4 và Thủ môn của người tham gia" },
  { key: PERMISSIONS.MATCH_SEED_MANAGE, name: "Quản lý seed theo trận", description: "Đánh giá và khóa seed trước khi chia đội" },
  { key: PERMISSIONS.MATCH_TEAMS_VIEW, name: "Xem đội hình", description: "Xem đội hình đã xác nhận của trận" },
  { key: PERMISSIONS.MATCH_TEAMS_MANAGE, name: "Quản lý chia đội", description: "Tạo, chỉnh và xác nhận phiên bản đội hình" },
  { key: PERMISSIONS.MATCH_FORM_REPORT_VIEW, name: "Xem phong độ suy luận", description: "Xem thống kê thắng thua suy luận từ khoản phạt" },
  { key: PERMISSIONS.CLUB_BALANCE_VIEW, name: "Xem số dư quỹ", description: "Xem số tiền quỹ hiện tại" },
  { key: PERMISSIONS.OTHER_MEMBER_BALANCES_VIEW, name: "Xem công nợ người khác", description: "Xem số dư của thành viên khác" },
  { key: PERMISSIONS.SETTINGS_MANAGE, name: "Quản lý cài đặt", description: "Cấu hình club, loại thu và QR" },
  { key: PERMISSIONS.USERS_MANAGE, name: "Quản lý tài khoản", description: "Tạo tài khoản, đặt lại mật khẩu và policy" },
  { key: PERMISSIONS.AUDIT_VIEW, name: "Xem chatter", description: "Xem lịch sử thay đổi" },
];

export const ROLE_LABELS = {
  ADMIN: "Admin",
  TREASURER: "Thủ quỹ",
  MEMBER: "Thành viên",
} as const;

export const ICON_OPTIONS = [
  { value: "futbol", label: "Bóng đá" },
  { value: "shirt", label: "Áo đấu" },
  { value: "person-running", label: "Cầu thủ chạy" },
  { value: "dumbbell", label: "Tập luyện" },
  { value: "trophy", label: "Cúp vô địch" },
  { value: "medal", label: "Huy chương" },
  { value: "award", label: "Giải thưởng" },
  { value: "flag", label: "Lá cờ" },
  { value: "stopwatch", label: "Đồng hồ bấm giờ" },
  { value: "calendar", label: "Lịch" },
  { value: "calendar-check", label: "Lịch đã xác nhận" },
  { value: "calendar-day", label: "Ngày thi đấu" },
  { value: "people-group", label: "Đội bóng" },
  { value: "wallet", label: "Ví tiền" },
  { value: "coins", label: "Tiền xu" },
  { value: "sack-dollar", label: "Túi tiền" },
  { value: "circle-dollar-to-slot", label: "Đóng quỹ" },
  { value: "hand-holding-dollar", label: "Thu tiền" },
  { value: "money-bill-wave", label: "Tiền mặt" },
  { value: "money-bill-transfer", label: "Chuyển khoản" },
  { value: "money-check-dollar", label: "Thanh toán" },
  { value: "credit-card", label: "Thẻ ngân hàng" },
  { value: "receipt", label: "Hóa đơn" },
  { value: "glass-water", label: "Ly nước" },
  { value: "bottle-water", label: "Chai nước" },
  { value: "droplet", label: "Giọt nước" },
  { value: "mug-hot", label: "Đồ uống nóng" },
  { value: "beer-mug-empty", label: "Bia" },
  { value: "champagne-glasses", label: "Liên hoan" },
  { value: "burger", label: "Đồ ăn" },
  { value: "pizza-slice", label: "Pizza" },
  { value: "utensils", label: "Ăn uống" },
  { value: "cake-candles", label: "Sinh nhật" },
  { value: "triangle-exclamation", label: "Cảnh báo / phạt" },
  { value: "circle-exclamation", label: "Nhắc nhở" },
  { value: "ban", label: "Vi phạm" },
  { value: "thumbs-down", label: "Không đạt" },
  { value: "thumbs-up", label: "Hoàn thành" },
  { value: "bolt", label: "Tốc độ / năng lượng" },
  { value: "gift", label: "Quà tặng" },
  { value: "heart", label: "Ủng hộ" },
  { value: "star", label: "Ngôi sao" },
  { value: "ticket", label: "Vé" },
  { value: "bullhorn", label: "Thông báo" },
  { value: "location-dot", label: "Địa điểm / sân" },
  { value: "bus", label: "Xe đội" },
  { value: "car", label: "Di chuyển" },
  { value: "briefcase-medical", label: "Y tế" },
  { value: "handshake", label: "Giao hữu / tài trợ" },
] as const;

export const ICON_ALLOWLIST: readonly string[] = ICON_OPTIONS.map((icon) => icon.value);
