import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowRightArrowLeft,
  faAward,
  faBars,
  faBan,
  faBeerMugEmpty,
  faBolt,
  faBottleWater,
  faBriefcaseMedical,
  faBullhorn,
  faBurger,
  faBus,
  faCakeCandles,
  faCalendar,
  faCalendarCheck,
  faCalendarDay,
  faCar,
  faCheck,
  faChampagneGlasses,
  faChartPie,
  faCircleDollarToSlot,
  faCircleExclamation,
  faCircleInfo,
  faCoins,
  faCopy,
  faCreditCard,
  faDroplet,
  faDumbbell,
  faEye,
  faFlag,
  faFutbol,
  faGear,
  faGift,
  faGlassWater,
  faHandHoldingDollar,
  faHandshake,
  faHeart,
  faHouse,
  faLocationDot,
  faList,
  faMagnifyingGlass,
  faMedal,
  faMoneyBill1Wave,
  faMoneyBillTransfer,
  faMoneyBillWave,
  faMoneyCheckDollar,
  faMugHot,
  faPeopleGroup,
  faPen,
  faPersonRunning,
  faPizzaSlice,
  faPlus,
  faReceipt,
  faRightFromBracket,
  faSackDollar,
  faShieldHalved,
  faShirt,
  faShoePrints,
  faStar,
  faStopwatch,
  faTableCellsLarge,
  faThumbsDown,
  faThumbsUp,
  faTicket,
  faTriangleExclamation,
  faTrash,
  faTrophy,
  faUser,
  faUsers,
  faUtensils,
  faWallet,
  type IconDefinition,
} from "@fortawesome/free-solid-svg-icons";

const icons: Record<string, IconDefinition> = {
  house: faHouse,
  wallet: faWallet,
  users: faUsers,
  user: faUser,
  "people-group": faPeopleGroup,
  coins: faCoins,
  copy: faCopy,
  calendar: faCalendar,
  "calendar-check": faCalendarCheck,
  "calendar-day": faCalendarDay,
  futbol: faFutbol,
  "person-running": faPersonRunning,
  dumbbell: faDumbbell,
  eye: faEye,
  "glass-water": faGlassWater,
  "bottle-water": faBottleWater,
  "mug-hot": faMugHot,
  "beer-mug-empty": faBeerMugEmpty,
  "champagne-glasses": faChampagneGlasses,
  "triangle-exclamation": faTriangleExclamation,
  "circle-exclamation": faCircleExclamation,
  info: faCircleInfo,
  ban: faBan,
  "thumbs-down": faThumbsDown,
  "thumbs-up": faThumbsUp,
  bolt: faBolt,
  "hand-holding-dollar": faHandHoldingDollar,
  "circle-dollar-to-slot": faCircleDollarToSlot,
  "sack-dollar": faSackDollar,
  shirt: faShirt,
  trophy: faTrophy,
  medal: faMedal,
  award: faAward,
  flag: faFlag,
  stopwatch: faStopwatch,
  droplet: faDroplet,
  "money-bill-wave": faMoneyBillWave,
  "money-bill-1-wave": faMoneyBill1Wave,
  "money-bill-transfer": faMoneyBillTransfer,
  "money-check-dollar": faMoneyCheckDollar,
  "credit-card": faCreditCard,
  receipt: faReceipt,
  burger: faBurger,
  "pizza-slice": faPizzaSlice,
  utensils: faUtensils,
  "cake-candles": faCakeCandles,
  gift: faGift,
  heart: faHeart,
  star: faStar,
  ticket: faTicket,
  bullhorn: faBullhorn,
  "location-dot": faLocationDot,
  bus: faBus,
  car: faCar,
  "briefcase-medical": faBriefcaseMedical,
  handshake: faHandshake,
  "shoe-prints": faShoePrints,
  transactions: faArrowRightArrowLeft,
  chart: faChartPie,
  settings: faGear,
  shield: faShieldHalved,
  logout: faRightFromBracket,
  plus: faPlus,
  edit: faPen,
  trash: faTrash,
  menu: faBars,
  check: faCheck,
  search: faMagnifyingGlass,
  list: faList,
  grid: faTableCellsLarge,
};

export function Icon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  return <FontAwesomeIcon icon={icons[name] ?? faWallet} className={className} />;
}
